apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abelqasm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abelqasm/abelqasm-app.git
    targetRevision: HEAD
    path: confs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true