Vagrant.configure(2) do |config|

  config.vm.box = "generic/alpine312"
  config.vm.synced_folder "./confs", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "abelqasmS" do |server|
    server.vm.hostname = "abelqasmS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "./scripts/server_script.sh"
  end

  config.vm.define "abelqasmW" do |worker|
    worker.vm.hostname = "abelqasmSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "./scripts/worker_script.sh"
  end
end