Vagrant.configure(2) do |config|

  config.vm.box = "generic/alpine312"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "abelqasmS" do |server|
    server.vm.hostname = "abelqasmS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", inline: "echo Hello world"
  end

  config.vm.define "abelqasmW" do |worker|
    worker.vm.hostmane = "abelqasmW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", inline: "echo Hello world"
  end
end