Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.boot_timeout = 1200

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024*8
    vb.cpus = 4
  end

  config.vm.define "abelqasmS" do |server|
    server.vm.hostname = "abelqasmS"
    server.vm.network "forwarded_port", guest: 8080, host: 8080 
    server.vm.network "forwarded_port", guest: 8181, host: 8181
  end
end