Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "abelqasm" do |control|
    control.vm.synced_folder "./confs", "/vagrant", type: "virtualbox"
    control.vm.hostname = "abelqasm"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2        
      vb.name = "abelqasm"
    end

    control.vm.provision "shell", path: "./scripts/script.sh"
  end
end