Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024*4   # 2GB RAM
    vb.cpus = 4
  end
  config.vm.define "abelqasmS" do |server|
    server.vm.hostname = "abelqasmS"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
  end 
end